#!/bin/sh

sxhkd &
dunst &
nitrogen --restore &
picom &
~/.config/polybar/bsp/launch.sh &
nm-applet &

#my_laptop_external_monitor=$(xrandr --query | grep -oP '^DP1 \K\w+')
#if [[ $my_laptop_external_monitor = connected ]]
#then
#    xrandr --output eDP1 --primary --mode 1366x768 --rotate normal --output DP1 --mode 1366x768 --rotate normal --left-of eDP1
#
#    bspc monitor eDP1 -d 1 2 3 4 5
#    bspc monitor DP1 -d 6 7 8 9 10
#else
#    bspc monitor eDP1 -d 1 2 3 4 5 6 7 8 9 10
#fi

bspc monitor eDP1 -d 1 2 3 4 5
#bspc monitor DP1 -d 6 7 8 9 10


bspc config border_width         2
bspc config window_gap           12
#bspc config top_padding          30

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle       true

bspc config normal_border_color   "#161821"
bspc config focused_border_color  "#95c4ce"
bspc config presel_feedback_color "#95c4ce"

bspc config focus_follows_pointer true

bspc rule -r '*'
bspc rule -a tk state=floating
bspc rule -a Tk state=floating
bspc rule -a matplotlib state=floating
bspc rule -a Matplotlib state=floating
bspc rule -a Toplevel state=floating
